name: Start Railway Bot

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 UTC = 9:00 CEST
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        run: curl -X POST https://railway.app/project/153a5642-a4a9-486f-8a24-325bb9ed461e/deploy \
             -H "Authorization: Bearer 5df7a434-186f-4b16-9149-a9d15ff7f54c"
