name: Stop Railway Bot

on:
  schedule:
    - cron: '0 21 * * *'  # 21:00 UTC = 23:00 CEST
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop bot
        run: curl -X PATCH https://backboard.railway.app/project/153a5642-a4a9-486f-8a24-325bb9ed461e/service/17a08243-84ab-4a90-8229-487a67b72d91/disable \
             -H "Authorization: Bearer 5df7a434-186f-4b16-9149-a9d15ff7f54c"
